### ISSUE TITLE
Apply autofixing to source files?

### ISSUE THREAD

**Issue by dryoma** [unindented/jscs-loader#11]
Hi!

jscs-loader now applies autofixing to its output code. But resulting builds are usually not suitable for convenient code reading (if not minified or changed in some other way, they at least contain webpack's loading code) and not supposed to be. 

So maybe it would make sence to autofix the source files, as the cli `jscs` does?

For example, [pragma-loader](https://www.npmjs.com/package/pragma-loader) does this by firing `fs.writeFile()`. Though I'm not sure if that is a correct behavior for a webpack loader.

**Comment by unindented** [comment]
@dryoma I hear you, but a Webpack loader changing your files... A loader is just a step in a transformation pipeline, it would feel weird to me if it started overwriting the source files.

**Comment by unindented** [comment]
I think I'll close this for now.

**Comment by dryoma** [comment]
Sorry for not responding, the notification probably got lost.

Sure, it was a mere suggestion. Modifying sources with a loader felt odd, yet I did find an example of doing this. Decided to give the thought a shot (=
