### ISSUE TITLE
Provide filename into error so reporter can use it

### ISSUE THREAD

**Issue by MoOx** [unindented/jscs-loader#2]
I like [GNU like message](https://www.gnu.org/prep/standards/html_node/Errors.html) and I would like to be able to output message like this

```
/.../filename.ext:line:column: message
```

Example:

```
web_modules/component/index.js:42:1337: This error make me sad (reason - code)
```

But right now I can not do that :(

**Comment by MoOx** [comment]
Adding `source` as param for the reporter should do the trick, don't you think ?

**Comment by unindented** [comment]
I agree with you. I'll look into this on the weekend. Thanks for your contributions!

**Comment by unindented** [comment]
Look at this JSCS reporter: https://github.com/jscs-dev/node-jscs/blob/b370466323d40517edc6f86cfbf4e5f4435fb2f3/lib/reporters/inline.js

That's how you get access to filename, row, column, etc.

**Comment by MoOx** [comment]
Already tried. filename return `input` since webpack provide the input directly (due to how loader works).
That's why I asked for this.

**Comment by unindented** [comment]
You are totally right, as usual. I'll reopen and look into this.

**Comment by unindented** [comment]
@MoOx I don't think there's a way for the loader to know the filename. `source` is just the contents of the file.

The best we may be able to do is just let the reporter use `emitError` and `emitWarning`:

```js
jscs: {
  reporter: function (errors) {
      if (!errors.isEmpty()) {
        errors.getErrorList().forEach(function(error) {
          this.emitWarning(util.format('line %d, col %d: %s',
            error.line, error.column, error.message));
        }, this);
      }
    }
}
```

```
WARNING in ./path/to/file.js
line 1, col 0: Multiple var declaration
```

What do you think?

**Comment by unindented** [comment]
I'm closing this, as I don't think there's a good way to solve this.
